package pl.sobczak.sports.models;

public enum PlayerPosition {

    GOALKEEPER,
    DEFENDER,
    DEFENDER_CENTRE_BACK,
    DEFENDER_SWEEPER,
    DEFENDER_FULL_BACK,
    DEFENDER_WING_BACK,
    MIDFIELDER,
    MIDFIELDER_CENTRE_MIDFIELD,
    MIDFIELDER_DEFENSIVE_MIDFIELD,
    MIDFIELDER_ATTACKING_MIDFIELD,
    MIDFIELDER_WIDE_MIDFIELD,
    FORWARD,
    FORWARD_CENTRE_FORWARD,
    FORWARD_SECOND_STRIKER,
    FORWARD_WINGER;
}
